//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoasp
{
    using System;
    using System.Collections.Generic;
    
    public partial class totalnew
    {
        public string Orderid { get; set; }
        public Nullable<int> total_bill { get; set; }
        public string orderdesc { get; set; }
        public Nullable<int> disAmt { get; set; }
    }
}
